import { jsPDF } from 'jspdf';

export function generateReportPdf(report) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const margin = 18;
  let y = margin;
  const pageW = doc.internal.pageSize.getWidth();
  const maxW = pageW - margin * 2;

  const line = (text, size = 10, bold = false) => {
    doc.setFont('helvetica', bold ? 'bold' : 'normal');
    doc.setFontSize(size);
    const lines = doc.splitTextToSize(String(text), maxW);
    lines.forEach((ln) => {
      if (y > 275) {
        doc.addPage();
        y = margin;
      }
      doc.text(ln, margin, y);
      y += size * 0.45 + 2;
    });
  };

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageW, 40, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text('AI Learning Authenticity Evaluator', margin, 18);
  doc.setFontSize(10);
  doc.text('Evaluation Report', margin, 28);
  y = 48;
  doc.setTextColor(30, 41, 59);

  line(`Evaluation ID: ${report.evaluationId}`, 9);
  line(`Date: ${new Date(report.completedAt).toLocaleString()}`, 9);
  y += 4;

  line('Student Information', 12, true);
  line(`Name: ${report.studentName || '—'}`, 10);
  line(`Student ID: ${report.studentId || '—'}`, 10);
  line(`Email: ${report.studentEmail || '—'}`, 10);
  line(`Assignment: ${report.assignmentTitle || '—'}`, 10);
  y += 4;

  line('Final Scores', 12, true);
  line(`Understanding / Overall: ${report.score?.overallScore ?? '—'}%`, 10);
  line(`Depth: ${report.score?.depthRating ?? '—'}`, 10);
  if (report.analytics) {
    line(`Confidence: ${report.analytics.confidenceScore}% | Originality: ${report.analytics.originalityScore}%`, 10);
    line(`Communication: ${report.analytics.communicationScore}% | Topic Mastery: ${report.analytics.topicMastery}%`, 10);
    line(`AI Suspicion: ${report.analytics.aiSuspicionLevel}%`, 10);
  }
  y += 4;

  if (report.aiDetection) {
    line('AI Content Detection', 12, true);
    line(`${report.aiDetection.verdict} (${report.aiDetection.aiProbability}% AI probability)`, 10);
    line(report.aiDetection.detailedReason, 9);
    y += 4;
  }

  line('Evaluation Summary', 12, true);
  line(report.score?.summary || '—', 10);
  y += 4;

  if (report.analytics?.weakAreas?.length) {
    line('Weak Concepts', 12, true);
    report.analytics.weakAreas.forEach((w) => line(`• ${w}`, 9));
    y += 4;
  }

  if (report.recommendations?.studyRoadmap) {
    line('Learning Roadmap', 12, true);
    line(report.recommendations.studyRoadmap, 10);
    y += 4;
  }

  line('Viva Q&A', 12, true);
  (report.qnas || []).forEach((q, i) => {
    line(`Q${i + 1}: ${q.question}`, 9, true);
    line(`A: ${q.answer || '(no answer)'}`, 9);
    line(`Feedback: ${q.feedback || '—'}`, 8);
    y += 2;
  });

  y = 285;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text(report.footer || 'Generated by AI Learning Authenticity Evaluator', margin, y);

  doc.save(`AuthentiViva-Report-${report.sessionId}.pdf`);
}
